service: nuxt-nitro
frameworkVersion: '4'

provider:
  name: aws
  region: ap-northeast-3
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 15
  architecture: arm64
  environment:
    NUXT_AWS_REGION: ap-northeast-3
    NUXT_SES_REGION: ap-northeast-1
    NUXT_MAIL_FROM: aiden@forma-global.com
    NUXT_MAIL_TO: liaiden1213@gmail.com
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

package:
  patterns:
    - '!**'
    - '.output/server/**'
    - 'node_modules/vue-bundle-renderer/**'
    - 'node_modules/@vue/shared/**'
    - 'package.json'

functions:
  web:
    handler: .output/server/index.handler
    events:
      - httpApi: '*'
