export const blogData = [
  {
    id: 1,
    title: "Lessons Learned from 07 Years in the Industry",
    date: "April 14, 2024",
    time: "3 Min Read",
    desc: "After spending over seven years in the tech industry, I've gathered a wealth of lessons about navigating both personal and professional growth in a rapidly changing field.",
    tags: ["Code", "Guides", "Tech", "Career"],
    image: "/images/blog-1.png",
  },
  {
    id: 2,
    title: "Balancing Creativity and Usability in Web Design",
    date: "April 15, 2024",
    time: "4 Min Read",
    desc: "Designing with a focus on both creativity and user experience can be challenging. In this article, I explore how to find the right balance for better web interfaces.",
    tags: ["Design", "Web", "UX/UI"],
    image: "/images/blog-2.png",
  },
  {
    id: 3,
    title: "The Future of Artificial Intelligence in Web Development",
    date: "April 16, 2024",
    time: "5 Min Read",
    desc: "AI technologies are quickly making their mark in web development. From automating repetitive tasks to enhancing user experience, here's how AI is shaping the future of the web.",
    tags: ["AI", "Tech", "Innovation"],
    image: "/images/blog-3.png",
  },
  {
    id: 4,
    title: "Building Scalable Web Applications with Microservices",
    date: "April 17, 2024",
    time: "6 Min Read",
    desc: "In today's fast-paced world, scalability is a critical factor for the success of any web application. Microservices offer a robust solution for building scalable and maintainable systems.",
    tags: ["Backend", "Microservices", "Scalability"],
    image: "/images/blog-4.png",
  },
  {
    id: 5,
    title: "The Evolution of JavaScript Frameworks in 2024",
    date: "April 18, 2024",
    time: "7 Min Read",
    desc: "As JavaScript frameworks continue to evolve, developers must stay up-to-date on the latest trends. In this post, we dive into the most popular frameworks of 2024 and their future potential.",
    tags: ["JavaScript", "Frameworks", "Web Development"],
    image: "/images/blog-2.png",
  },
  {
    id: 6,
    title: "How to Build a Personal Brand as a Developer",
    date: "April 19, 2024",
    time: "5 Min Read",
    desc: "Building a personal brand as a developer can open up opportunities for growth, networking, and career advancement. This guide will help you develop your brand in the tech community.",
    tags: ["Career", "Personal Branding", "Development"],
    image: "/images/blog-3.png",
  },
];
